config/routes.rb
UltimateWhip::Application.routes.draw do
  require 'sidekiq/web'

  namespace :api do ## Used for Ajax purposes
    namespace :v1 do
      resources :comments
      resources :garages
      resources :showcases, only: [:index]
      resources :tags, only: [:index]
      resources :photos do
        collection do
          get "file_name"
        end
      end
    end
  end

  resources :photos, only: [:show,:new, :index]
  resources :tags, only: [:show, :new]
  resources :landings, only: [:show]

  resources :garages
  resources :garage_photos
  resources :makes, only: [:show]
  resources :registration_succesful, only: [:index]
  resources :users, only: [:update]
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "whips#index"


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/shared/_flash.html.erb
<% flash.each do |flash_notice| %>
  <div class="alert alert-<%= flash_notice[0] %>">
    <button type="button" class="close">&times;</button>
    <%= flash_notice[1] %>
  </div>
<% end %>

app/views/shared/_login_dropdown.html.slim
= form_tag user_session_path, class: "navbar-form login-form" do
  h4 Login
  = text_field_tag 'user[email]', nil, placeholder: "Email"
  = password_field_tag 'user[password]', nil, placeholder: "Password"
  button(class="btn btn-primary") Sign in
  hr
  = link_to "Forgot your password?", new_password_path('user')
  br
  = link_to "Signup?", new_user_registration_path

app/views/shared/_manage_pills.html.slim
ul.nav.nav-pills
  li(class="#{'active' if current_tab?('new')}")
    = link_to "Add", new_photo_path
  li(class="#{'active' if current_tab?('index')}")
    = link_to "Modify", photos_path

app/views/shared/_navbar.html.slim
nav.navbar
  a.logo href="/"
    = image_tag 'Auxotic-Logo-Header.png', alt: 'auxotic logo'
  .register-area
    .toggle-login
      i.icon-reorder.icon-2x
    #search-area
    .register
      - if current_user
        li= link_to "+ Photos", new_photo_path
        li= link_to('Logout', destroy_user_session_path, :method => :delete)
      - else
        li= link_to "Sign Up", new_user_registration_path
        li= link_to "Sign In", new_user_session_path